### ISSUE TITLE
it is actually a bit delayed

### ISSUE THREAD

**Issue by DissonancePM** [SkippsDev/RealTime-OTP#2]
you said it would be real time and it's not flagged and disliked

**Comment by DissonancePM** [comment]
by the way my lua otp server is better than yours

**Comment by DissonancePM** [comment]
issue resolved by not using realtime-otp

**Comment by xseano** [comment]
wait you know how to code? osrry

**Comment by xseano** [comment]
only skrubs use lua, get gud pleb

**Comment by xseano** [comment]
do you even know what realtime means?

**Comment by DissonancePM** [comment]
yeh it means not delay 
dd xddDDDDDDDS

**Comment by xseano** [comment]
![image](https://cloud.githubusercontent.com/assets/16991015/21465848/7258e3b4-c968-11e6-8c04-dd7e1d352689.png)

wat

was project altis delahyed?
http://www.projectaltis.com/

**Comment by SodiumFine** [comment]
this is cancer

**Comment by xseano** [comment]
`  messenger.send('setShipTimer-%s' % self.getDoId(), [
            self.getTimeLeft()])`

**Comment by SodiumFine** [comment]
def loadGradient(parent, frame, hue, minSat, maxSat, minVal, maxVal):

**Comment by SodiumFine** [comment]
`x *= j
                y *= j`

**Comment by xseano** [comment]
`'maxSpeed': 0.8 * defaultMaxSpeed,
        'reverseAcceleration': 0.7 * defaultReverseAcceleration,`

**Comment by SodiumFine** [comment]
`np2 = np.getParent().attachNewNode(np.node().generate())`

**Comment by SodiumFine** [comment]
im da best

**Comment by xseano** [comment]
`'sp': 8000,
        'maxCargo': 12,`

**Comment by SodiumFine** [comment]
`map(lambda c: c.setX(c.getX() - x / 2), root.getChildren())`

**Comment by SodiumFine** [comment]
`icup`

**Comment by xseano** [comment]
spell 

> icup

**Comment by SodiumFine** [comment]
nigga

**Comment by xseano** [comment]
# spell icup

**Comment by SodiumFine** [comment]
**# 

1. SPELL ICUP
2. NIGGA

**

**Comment by SodiumFine** [comment]
# _**SPELL ICUP NIGGA**_

**Comment by xseano** [comment]
# sa9iling

> ov, ai, client, ud

**Comment by SodiumFine** [comment]
1. Spell Icup
2. Spell Icup

**Comment by SodiumFine** [comment]
@xseano @SkippsDev icup icup icup

**Comment by xseano** [comment]
s## asd

**Comment by SodiumFine** [comment]
#1 <-- icup material

**Comment by SodiumFine** [comment]
- [ ] 

- [ ] 

- [ihop ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by xseano** [comment]
# @DissonancePM  @SkippsDev  ]]# Spell ICUP

**Comment by SodiumFine** [comment]
[icup icup](url)

**Comment by SodiumFine** [comment]
**# The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.**

**Comment by SodiumFine** [comment]
# **The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.**

**Comment by xseano** [comment]
# RainDrops = RainDrops
                import pirates.effects.RainDrops
                self.rainDrops = RainDrops(base.camera)
                self.rainDrops.reparentTo(render)
                self.rainDrops.startLoop()
                RainMist = RainMist
                import pirates.effects.RainMist
                self.rainMist = RainMist(base.camera)
                self.rainMist.reparentTo(render)
                self.rainMist.startLoop()
                RainSplashes = RainSplashes
                import pirates.effects.RainSplashes
                self.rainSplashes = RainSplashes(base.camera)
                self.rainSplashes.reparentTo(render)
                self.rainSplashes.startLoop()
                RainSplashes2 = RainSplashes2
                import pirates.effects.RainSplashes2
                self.rainSplashes2 = RainSplashes2(base.camera)
                self.rainSplashes2.reparentTo(render)
                self.rainSplashes2.startLoop()

**Comment by SodiumFine** [comment]
# **I am the one, don't weigh a ton
Don't need a gun to get respect up on the street
Under the sun, the bastard son
Will pop the Glock to feed himself and family
By any means, your enemies my enemies
We wet them up like a canteen
The yellow tape surrounds the fate
Don't have a face so now you late, open the gates

Great, eliminate like ElimiDate
Hey, young boy had to penetrate
Face, young boy done caught a case
Bang, now his mama living with the pain
Wait, doctor says he's gonna stay
Let him get the sensu bean so he regenerate
Now a nigga harder than the head of the state
Denzel Curry is the new candidate
Ultimate, alternate, you are the opposite
Stop this shit, chop your esophagus
Bitches be bopping it, bow down and popping it
Dropping it in her esophagus
She get so nasty, in public she classy
Perhaps she is able to swallow it
Girl, I can make you a star
Then I put her ass on Apollo, bitch
Bitch, I am ultimate, behold my awesomeness
Narcissist, part time an arsonist
Ripping through cartilage, I am the hardest, bitch
Wrap it up, put in sarcophagus

Dearly departed, it's done when it started

So now that I'm living so harmonious

Feeling like Spartacus, Curry the ultimate

I am the best, there's no politics, bitch, I'm ultimate

ultimate
bitch I'm
I am the one, don't weigh a ton
Don't need a gun to get respect up on the street
Under the sun, the bastard son
Will pop the Glock to feed himself and family
By any means, your enemies my enemies
We wet them up like a canteen
The yellow tape surrounds the fate
Don't have a face so now you late, open the gates
Ultimate, infinite, flow is opium
Open the internet, photosynthesis
Put up parentheses, temporary
Very scary if I feel like Dirty Harry
Just might bust a bitch, never knew my life
But yet the question is is he fake, is he real
What the message is, chop a bitch nigga up
I'ma sever it when I sever shit
I kill 'em, no Kony, these niggas ain't homies
Claim you the homie, I turn into Broly
Dropping melodic, enter the cosmic
Flow like a prophet, lyrical toxic
Flow like a foreigner, I'm the torturer
Out of South Florida, call the coroner
Killed in the corridor, I'm the overlord
Rhymes like a sorcerer, I'm an animorph
Bitch, I'm a beast
Nigga, you tell me who fucking with me
K to the I to the N to the G
Claim you the hottest, but I disagree
Better love something than get a degree
This for lord infamous so R.I.P
Arrivederci, bitches looking thirsty, riding through the dirty
Like it's mandatory, ending of the story
I am the one, don't weigh a ton
Don't need a gun to get respect up on the street
Under the sun, the bastard son
Will pop the Glock to feed himself and family
By any means, your enemies my enemies
We wet them up like a canteen
The yellow tape surrounds the fate
Don't have a face so now you late, open the gates**

**Comment by SodiumFine** [comment]
# I am the one, don't weigh a ton Don't need a gun to get respect up on the street Under the sun, the bastard son Will pop the Glock to feed himself and family By any means, your enemies my enemies We wet them up like a canteen The yellow tape surrounds the fate Don't have a face so now you late, open the gates Great, eliminate like ElimiDate Hey, young boy had to penetrate  Face, young boy done caught a case Bang, now his mama living with the pain Wait, doctor says he's gonna stay Let him get the sensu bean so he regenerate Now a nigga harder than the head of the state Denzel Curry is the new candidate Ultimate, alternate, you are the opposite Stop this shit, chop your esophagus Bitches be bopping it, bow down and popping it Dropping it in her esophagus She get so nasty, in public she classy Perhaps she is able to swallow it Girl, I can make you a star Then I put her ass on Apollo, bitch Bitch, I am ultimate, behold my awesomeness Narcissist, part time an arsonist Ripping through cartilage, I am the hardest, bitch Wrap it up, put in sarcophagus Dearly departed, it's done when it started So now that I'm living so harmonious Feeling like Spartacus, Curry the ultimate I am the best, there's no politics, bitch, I'm ultimate ultimate bitch I'm I am the one, don't weigh a ton Don't need a gun to get respect up on the street Under the sun, the bastard son Will pop the Glock to feed himself and family By any means, your enemies my enemies We wet them up like a canteen The yellow tape surrounds the fate Don't have a face so now you late, open the gates Ultimate, infinite, flow is opium Open the internet, photosynthesis Put up parentheses, temporary Very scary if I feel like Dirty Harry Just might bust a bitch, never knew my life But yet the question is is he fake, is he real What the message is, chop a bitch nigga up I'ma sever it when I sever shit I kill 'em, no Kony, these niggas ain't homies Claim you the homie, I turn into Broly Dropping melodic, enter the cosmic Flow like a prophet, lyrical toxic Flow like a foreigner, I'm the torturer Out of South Florida, call the coroner Killed in the corridor, I'm the overlord Rhymes like a sorcerer, I'm an animorph Bitch, I'm a beast Nigga, you tell me who fucking with me K to the I to the N to the G Claim you the hottest, but I disagree Better love something than get a degree This for lord infamous so R.I.P Arrivederci, bitches looking thirsty, riding through the dirty Like it's mandatory, ending of the story I am the one, don't weigh a ton Don't need a gun to get respect up on the street Under the sun, the bastard son Will pop the Glock to feed himself and family By any means, your enemies my enemies We wet them up like a canteen The yellow tape surrounds the fate Don't have a face so now you late, open the gates

**Comment by roke-william** [comment]
huh

**Comment by DissonancePM** [comment]
@xseano ey project altis delay by permanent auth cookie xddddddddd security

**Comment by roke-william** [comment]
XPPPPPPPP

**Comment by DissonancePM** [comment]
ey if this realtim ohteepee does mean originale not railteam?

**Comment by xseano** [comment]
@DissonancePM  more liek oauth -2.0 security xdxdxdxdxdxd, i liek xml toon data

**Comment by xseano** [comment]
railteam not,i think delay ohtpee
